# Generated by Django 5.0.2 on 2024-03-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
