# Generated by Django 5.0.2 on 2024-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
